export interface BookMetadata {
    id: number;
    name: string;
    testament: "Old" | "New";
    chapters: number;
}

export const BOOKS: Record<number, BookMetadata> = {
    1: { id: 1, name: "Genesis", testament: "Old", chapters: 50 },
    2: { id: 2, name: "Exodus", testament: "Old", chapters: 40 },
    3: { id: 3, name: "Leviticus", testament: "Old", chapters: 27 },
    4: { id: 4, name: "Numbers", testament: "Old", chapters: 36 },
    5: { id: 5, name: "Deuteronomy", testament: "Old", chapters: 34 },
    6: { id: 6, name: "Joshua", testament: "Old", chapters: 24 },
    7: { id: 7, name: "Judges", testament: "Old", chapters: 21 },
    8: { id: 8, name: "Ruth", testament: "Old", chapters: 4 },
    9: { id: 9, name: "1 Samuel", testament: "Old", chapters: 31 },
    10: { id: 10, name: "2 Samuel", testament: "Old", chapters: 24 },
    11: { id: 11, name: "1 Kings", testament: "Old", chapters: 22 },
    12: { id: 12, name: "2 Kings", testament: "Old", chapters: 25 },
    13: { id: 13, name: "1 Chronicles", testament: "Old", chapters: 29 },
    14: { id: 14, name: "2 Chronicles", testament: "Old", chapters: 36 },
    15: { id: 15, name: "Ezra", testament: "Old", chapters: 10 },
    16: { id: 16, name: "Nehemiah", testament: "Old", chapters: 13 },
    17: { id: 17, name: "Esther", testament: "Old", chapters: 10 },
    18: { id: 18, name: "Job", testament: "Old", chapters: 42 },
    19: { id: 19, name: "Psalms", testament: "Old", chapters: 150 },
    20: { id: 20, name: "Proverbs", testament: "Old", chapters: 31 },
    21: { id: 21, name: "Ecclesiastes", testament: "Old", chapters: 12 },
    22: { id: 22, name: "Song of Solomon", testament: "Old", chapters: 8 },
    23: { id: 23, name: "Isaiah", testament: "Old", chapters: 66 },
    24: { id: 24, name: "Jeremiah", testament: "Old", chapters: 52 },
    25: { id: 25, name: "Lamentations", testament: "Old", chapters: 5 },
    26: { id: 26, name: "Ezekiel", testament: "Old", chapters: 48 },
    27: { id: 27, name: "Daniel", testament: "Old", chapters: 12 },
    28: { id: 28, name: "Hosea", testament: "Old", chapters: 14 },
    29: { id: 29, name: "Joel", testament: "Old", chapters: 3 },
    30: { id: 30, name: "Amos", testament: "Old", chapters: 9 },
    31: { id: 31, name: "Obadiah", testament: "Old", chapters: 1 },
    32: { id: 32, name: "Jonah", testament: "Old", chapters: 4 },
    33: { id: 33, name: "Micah", testament: "Old", chapters: 7 },
    34: { id: 34, name: "Nahum", testament: "Old", chapters: 3 },
    35: { id: 35, name: "Habakkuk", testament: "Old", chapters: 3 },
    36: { id: 36, name: "Zephaniah", testament: "Old", chapters: 3 },
    37: { id: 37, name: "Haggai", testament: "Old", chapters: 2 },
    38: { id: 38, name: "Zechariah", testament: "Old", chapters: 14 },
    39: { id: 39, name: "Malachi", testament: "Old", chapters: 4 },
    40: { id: 40, name: "Matthew", testament: "New", chapters: 28 },
    41: { id: 41, name: "Mark", testament: "New", chapters: 16 },
    42: { id: 42, name: "Luke", testament: "New", chapters: 24 },
    43: { id: 43, name: "John", testament: "New", chapters: 21 },
    44: { id: 44, name: "Acts", testament: "New", chapters: 28 },
    45: { id: 45, name: "Romans", testament: "New", chapters: 16 },
    46: { id: 46, name: "1 Corinthians", testament: "New", chapters: 16 },
    47: { id: 47, name: "2 Corinthians", testament: "New", chapters: 13 },
    48: { id: 48, name: "Galatians", testament: "New", chapters: 6 },
    49: { id: 49, name: "Ephesians", testament: "New", chapters: 6 },
    50: { id: 50, name: "Philippians", testament: "New", chapters: 4 },
    51: { id: 51, name: "Colossians", testament: "New", chapters: 4 },
    52: { id: 52, name: "1 Thessalonians", testament: "New", chapters: 5 },
    53: { id: 53, name: "2 Thessalonians", testament: "New", chapters: 3 },
    54: { id: 54, name: "1 Timothy", testament: "New", chapters: 6 },
    55: { id: 55, name: "2 Timothy", testament: "New", chapters: 4 },
    56: { id: 56, name: "Titus", testament: "New", chapters: 3 },
    57: { id: 57, name: "Philemon", testament: "New", chapters: 1 },
    58: { id: 58, name: "Hebrews", testament: "New", chapters: 13 },
    59: { id: 59, name: "James", testament: "New", chapters: 5 },
    60: { id: 60, name: "1 Peter", testament: "New", chapters: 5 },
    61: { id: 61, name: "2 Peter", testament: "New", chapters: 3 },
    62: { id: 62, name: "1 John", testament: "New", chapters: 5 },
    63: { id: 63, name: "2 John", testament: "New", chapters: 1 },
    64: { id: 64, name: "3 John", testament: "New", chapters: 1 },
    65: { id: 65, name: "Jude", testament: "New", chapters: 1 },
    66: { id: 66, name: "Revelation", testament: "New", chapters: 22 },
};

export function getBookInfo(id: number): BookMetadata {
    return BOOKS[id] || { id, name: `Book ${id}`, testament: "Old", chapters: 1 };
}
